services:
  app:
    environment:
      DB_HOST: db
      MIX_ENV: "dev"
    build: .
    env_file: .env
    ports:
      - "4000:4000"
    volumes:
      - /opt/app/assets/node_modules
      - /opt/app/deps
      - .:/opt/app
    depends_on:
      - db
  db:
    image: postgres:15.7
    environment:
      POSTGRES_PASSWORD: password1
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg_data:
