version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.9.4
      - image: circleci/postgres:11.6
        environment:
          POSTGRES_USER: pair
          POSTGRES_DB: edgebuilder_test
          POSTGRES_PASSWORD:

    working_directory: ~/app
    steps:
      - checkout

      - run: mix local.hex --force
      - run: mix local.rebar --force

      - restore_cache:
          keys:
            - v2-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v2-mix-cache-{{ .Branch }}
            - v2-mix-cache
      - restore_cache:
          keys:
            - v2-build-cache-{{ .Branch }}
            - v2-build-cache

      - run: mix do deps.get, compile

      - save_cache:
          key: v2-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: ["deps"]
      - save_cache:
          key: v2-mix-cache-{{ .Branch }}
          paths: ["deps"]
      - save_cache:
          key: v2-mix-cache
          paths: ["deps"]
      - save_cache:
          key: v2-build-cache-{{ .Branch }}
          paths: ["_build"]
      - save_cache:
          key: v2-build-cache
          paths: ["_build"]

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Install psql
          command: sudo apt-get update && sudo apt-get install postgresql-client

      - run:
          name: Run tests
          command: bash .circleci/run-tests.sh

      - run:
          name: Upload coverage report to Codecov
          command: bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: _build/test/lib/edge_builder
